---
title: "Dungeons and DragRacers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(jsonlite)
library(tidyverse)
library(scales)
library(lubridate)


my_url <- paste0("https://www.dnd5eapi.co/api/classes/barbarian")

my_raw <- httr::GET(my_url)

str(my_raw)
str(my_raw$content)

my_content <- httr::content(my_raw, as = 'text')
str(my_content)



my_content_from_json <- jsonlite::fromJSON(my_content)

glimpse(my_content_from_json)

my_content_from_json$proficiencies$index



spells_raw <- paste0("https://www.dnd5eapi.co/api/spells/tongues")

spells_get <- httr::GET(spells_raw)

str(spells_get)

spells_df <- httr::content(spells_get, as = 'text')

str(spells_df)

spells_df <- jsonlite::fromJSON(spells_df)

glimpse(spells_df)

```



```{r}

monsters_raw <- paste0("https://www.dnd5eapi.co/api/monsters")

monsters_get <- httr::GET(monsters_raw)

str(monsters_get)

monsters_content <- httr::content(monsters_get, as = "text")

str(monsters_content)

monster_json <- jsonlite::fromJSON(monsters_content, flatten = TRUE)

glimpse(monster_json)

monster_json$results$name










mari_raw <- paste0("https://www.dnd5eapi.co/api/monsters/marilith")

mari_get <- httr::GET(mari_raw)

str(mari_get)

mari_content <- httr::content(mari_get, as = "text")

str(mari_content)

mari_json <- jsonlite::fromJSON(mari_content, flatten = TRUE)

glimpse(mari_json)


mari_json$damage_resistances

```

